name: 'Test multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  test-on-linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/developmententity/gcp-cloud-tools:initial
      options:
        -v /dev:/dev
        -u root

    steps:
      - name: 'Docker image test'
        shell: bash
        run: |
          echo -ne "ANSIBLE_CLI_VERSION="
          ansible --version | awk -F"core " '/core/{print "v"$2}' | sed 's/]//'
          echo -ne "HELM_CLI_VERSION="
          helm version --short | awk -F'+' '{print $1}'
          echo -ne "K9S_CLI_VERSION="
          k9s version | awk '/Version:/ {print $2}'
          echo -ne "KOPS_CLI_VERSION="
          kops version | awk -F'git-' 'NR==1 {print $2}' | sed 's/)//'
          echo -ne "KUBECTL_CLI_VERSION="
          kubectl version --client | awk -F': ' 'NR==1 {print $2}'
          echo -ne "TERRAFORM_CLI_VERSION="
          terraform version | awk -F'v' 'NR==1 {print $2}'
          echo -ne "TERRAGRUNT_CLI_VERSION="
          terragrunt --version | awk 'NR==1 {print $NF}'
          echo -ne "GCLOUD_CLI_VERSION="
          gcloud version | awk '/Google Cloud SDK/{print $NF}'
