name: 'Test multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  test-on-linux-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/developmententity/gcp-cloud-tools:initial
      options:
        -v /dev:/dev

    steps:
      - name: 'Docker image test (amd64)'
        run: |
          ansible --version
          aws --version
          session-manager-plugin --version
          sam --version
          helm version
          kops version
          kubectl version --client
          k9s version
          terraform version
          terragrunt --version
          gcloud version

  test-on-linux-arm:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/developmententity/gcp-cloud-tools:initial
      options:
        -v /dev:/dev

    steps:
      - name: 'Docker image test (arm64)'
        run: |
          ansible --version
          aws --version
          session-manager-plugin --version
          sam --version
          helm version
          kops version
          kubectl version --client
          k9s version
          terraform version
          terragrunt --version
          gcloud version

  test-on-mac-via-colima:
    runs-on: macos-latest
    steps:
      - name: 'Install Colima and Docker'
        run: |
          brew install docker docker-compose colima
          colima start --arch arm64
      - name: Docker info
        run: |
          docker info
      - name: 'Pull Docker image from Docker Hub'
        run: |
          docker pull docker.io/developmententity/gcp-cloud-tools:initial
      - name: 'Run Docker image test (arm64)'
        run: |
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "ansible --version"
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "aws --version"
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "session-manager-plugin --version"
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "sam --version"
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "helm version"
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "kops version"
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "kubectl version --client"
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "k9s version"
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "terragrunt --version"
          docker run --entrypoint "/bin/sh" --network=none --rm --name gcp-cloud-test docker.io/developmententity/gcp-cloud-tools:initial -c "gcloud version"
