name: 'Test multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  test-on-linux-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/developmententity/gcp-cloud-tools:initial
      options:
        -v /dev:/dev

    steps:
      - name: 'Docker image test (amd64)'
        run: |
          #ansible --version
          helm version
          kops version
          kubectl version --client
          k9s version
          terraform version
          terragrunt --version
          gcloud version

  test-on-linux-arm:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/developmententity/gcp-cloud-tools:initial
      options:
        -v /dev:/dev

    steps:
      - name: 'Docker image test (arm64)'
        run: |
          #ansible --version
          helm version
          kops version
          kubectl version --client
          k9s version
          terraform version
          terragrunt --version
          gcloud version
